### ISSUE TITLE
Windows target corrupts memory when attempting to load huge asset library

### ISSUE THREAD

**Issue by space-nuko** [native-toolkit/lime#1525]
I also posted this issue at https://github.com/HaxeFoundation/hxcpp/issues/986, but I'll repost it here in case it helps

I'm trying to load a large asset library in openfl from autogenerated swf assets. The html5 target works fine but the Windows target corrupts the heap on two different setups I have. With ASAN enabled it crashes on the call to `Assets.loadLibrary()`.

Here is a minimal repro. The `.json` file in this case is about 20MB in size

```hx
package;

import openfl.display.Sprite;
import lime.utils.Bytes;
import haxe.Json;

class Main extends Sprite {
	public function new() {
		super();

                var bytes = Bytes.fromFile("C:/path/to/huge.json");
                var s = bytes.getString(0, bytes.length);
                Json.parse(s);
	}
}
```

I also used these defines:

```xml
    <haxedef name="HXCPP_CHECK_POINTER" if="cpp"/>
    <haxedef name="HXCPP_STACK_LINE" if="cpp"/>
    <haxedef name="HXCPP_STACK_TRACE" if="cpp"/>
    <haxedef name="HXCPP_DEBUG_LINK" if="cpp"/>
    <haxedef name="HXCPP_CATCH_SEGV" if="cpp"/>
```

And enabled ASAN in `.hxcpp_config.xml`:

```xml
     <compiler id="MSVC" if="windows">
        <flag value = "/fsanitize=address"/>
     </compiler>
```

<details><summary>Traceback</summary>
<pre>
Running command: RUN
 - Changing directory: Export/windows/bin/
 - Running command: AddingAnimation.exe -verbose -livereload
[lime.utils.Preloader] Preloading asset library: default
[lime.utils.Preloader] Loaded asset library: default [1/1]
[lime.utils.Preloader] Preload complete
=================================================================
==88280==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x00795d8f4ba0 at pc 0x7ff7f8867423 bp 0x00795d8f4390 sp 0x00795d8f4398
READ of size 8 at 0x00795d8f4ba0 thread T0
    #0 0x7ff7f8867422 in hx::MarkConservative(int *, int *, class hx::MarkContext *) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:5554
    #1 0x7ff7f8899e71 in LocalAllocator::Mark(class hx::MarkContext *) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:6219
    #2 0x7ff7f886a3bc in MarkLocalAlloc C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:6297
    #3 0x7ff7f889a6e0 in GlobalAllocator::MarkAll(bool) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:4677
    #4 0x7ff7f88957b2 in GlobalAllocator::Collect(bool, bool, bool, bool) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:4847
    #5 0x7ff7f8897e81 in GlobalAllocator::GetFreeBlock(int, class hx::ImmixAllocator *) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:3530
    #6 0x7ff7f8894d89 in LocalAllocator::CallAlloc(int, unsigned int) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:6156
    #7 0x7ff7f73261a2 in hx::ImmixAllocator::alloc(class hx::ImmixAllocator *, unsigned __int64, bool, char const *) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\GC.h:428
    #8 0x7ff7f73247e9 in hx::Object::operator new(unsigned __int64, bool, char const *) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\Object.h:170
    #9 0x7ff7f87c6b7f in hx::Object::operator new(unsigned __int64, enum hx::NewObjectType, char const *) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\Object.h:187
    #10 0x7ff7f87c6b24 in hx::IntData::operator new(unsigned __int64, enum hx::NewObjectType, char const *) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\Dynamic.cpp:58
    #11 0x7ff7f87c447e in fromInt C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\Dynamic.cpp:372
    #12 0x7ff7f87ad1ab in Dynamic::Dynamic(int) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\Dynamic.cpp:381
    #13 0x7ff7f8492cee in haxe::format::JsonParser_obj::parseRec(void) C:\Users\chii\build\stringtest\Export\windows\obj\src\haxe\format\JsonParser.cpp:214
    #14 0x7ff7f84941a5 in haxe::format::JsonParser_obj::parseRec(void) C:\Users\chii\build\stringtest\Export\windows\obj\src\haxe\format\JsonParser.cpp:372
    #15 0x7ff7f8493194 in haxe::format::JsonParser_obj::parseRec(void) C:\Users\chii\build\stringtest\Export\windows\obj\src\haxe\format\JsonParser.cpp:252
    #16 0x7ff7f84941a5 in haxe::format::JsonParser_obj::parseRec(void) C:\Users\chii\build\stringtest\Export\windows\obj\src\haxe\format\JsonParser.cpp:372
    #17 0x7ff7f8493194 in haxe::format::JsonParser_obj::parseRec(void) C:\Users\chii\build\stringtest\Export\windows\obj\src\haxe\format\JsonParser.cpp:252
    #18 0x7ff7f84941a5 in haxe::format::JsonParser_obj::parseRec(void) C:\Users\chii\build\stringtest\Export\windows\obj\src\haxe\format\JsonParser.cpp:372
    #19 0x7ff7f8493194 in haxe::format::JsonParser_obj::parseRec(void) C:\Users\chii\build\stringtest\Export\windows\obj\src\haxe\format\JsonParser.cpp:252
    #20 0x7ff7f84941a5 in haxe::format::JsonParser_obj::parseRec(void) C:\Users\chii\build\stringtest\Export\windows\obj\src\haxe\format\JsonParser.cpp:372
    #21 0x7ff7f8491b70 in haxe::format::JsonParser_obj::doParse(void) C:\Users\chii\build\stringtest\Export\windows\obj\src\haxe\format\JsonParser.cpp:51
    #22 0x7ff7f77b23f4 in Main_obj::__construct(void) C:\Users\chii\build\stringtest\Export\windows\obj\src\Main.cpp:47
    #23 0x7ff7f80e0711 in DocumentClass_obj::__construct(class hx::ObjectPtr<class openfl::display::DisplayObjectContainer_obj>) C:\Users\chii\build\stringtest\Export\windows\obj\src\DocumentClass.cpp:39
    #24 0x7ff7f80e0d78 in DocumentClass_obj::__alloc(class hx::ImmixAllocator *, class hx::ObjectPtr<class openfl::display::DisplayObjectContainer_obj>) C:\Users\chii\build\stringtest\Export\windows\obj\src\DocumentClass.cpp:84
    #25 0x7ff7f865d1a1 in ApplicationMain_obj::start(class hx::ObjectPtr<class openfl::display::Stage_obj>) C:\Users\chii\build\stringtest\Export\windows\obj\src\ApplicationMain.cpp:312
    #26 0x7ff7f865e81f in `ApplicationMain_obj::create'::`2'::_hx_Closure_2::_hx_run C:\Users\chii\build\stringtest\Export\windows\obj\src\ApplicationMain.cpp:167
    #27 0x7ff7f865ea41 in `ApplicationMain_obj::create'::`2'::_hx_Closure_2::__run C:\Users\chii\build\stringtest\Export\windows\obj\src\ApplicationMain.cpp:169
    #28 0x7ff7f81e7c36 in lime::app::_Event_Void_Void_obj::dispatch(void) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140f67c36)
    #29 0x7ff7f853c90e in openfl::display::Preloader_obj::display_onUnload(class hx::ObjectPtr<class openfl::events::Event_obj>) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1412bc90e)
    #30 0x7ff7f853ab5a in openfl::display::Preloader_obj::__Mark(class hx::MarkContext *) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1412bab5a)
    #31 0x7ff7f87cdc58 in hx::CMemberFunction1::__run(class Dynamic const &) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\DynamicImpl.h:151
    #32 0x7ff7f79510bd in openfl::events::EventDispatcher_obj::_hx___dispatchEvent(class hx::ObjectPtr<class openfl::events::Event_obj>) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1406d10bd)
    #33 0x7ff7f82a193f in openfl::display::DisplayObject_obj::_hx___dispatchEvent(class hx::ObjectPtr<class openfl::events::Event_obj>) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x14102193f)
    #34 0x7ff7f82a216f in openfl::display::DisplayObject_obj::_hx___dispatchWithCapture(class hx::ObjectPtr<class openfl::events::Event_obj>) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x14102216f)
    #35 0x7ff7f82a8759 in openfl::display::DisplayObject_obj::dispatchEvent(class hx::ObjectPtr<class openfl::events::Event_obj>) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x141028759)
    #36 0x7ff7f85c4eba in openfl::display::DefaultPreloader_obj::onLoaded(void) C:\Users\chii\build\stringtest\Export\windows\obj\src\openfl\display\DefaultPreloader.cpp:213
    #37 0x7ff7f85c688a in openfl::display::DefaultPreloader_obj::this_onComplete(class hx::ObjectPtr<class openfl::events::Event_obj>) C:\Users\chii\build\stringtest\Export\windows\obj\src\openfl\display\DefaultPreloader.cpp:252
    #38 0x7ff7f85c761b in openfl::display::__DefaultPreloader_objthis_onComplete C:\Users\chii\build\stringtest\Export\windows\obj\src\openfl\display\DefaultPreloader.cpp:256
    #39 0x7ff7f87cdc58 in hx::CMemberFunction1::__run(class Dynamic const &) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\DynamicImpl.h:151
    #40 0x7ff7f79510bd in openfl::events::EventDispatcher_obj::_hx___dispatchEvent(class hx::ObjectPtr<class openfl::events::Event_obj>) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1406d10bd)
    #41 0x7ff7f82a193f in openfl::display::DisplayObject_obj::_hx___dispatchEvent(class hx::ObjectPtr<class openfl::events::Event_obj>) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x14102193f)
    #42 0x7ff7f82a216f in openfl::display::DisplayObject_obj::_hx___dispatchWithCapture(class hx::ObjectPtr<class openfl::events::Event_obj>) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x14102216f)
    #43 0x7ff7f82a8759 in openfl::display::DisplayObject_obj::dispatchEvent(class hx::ObjectPtr<class openfl::events::Event_obj>) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x141028759)
    #44 0x7ff7f853cc42 in openfl::display::Preloader_obj::start(void) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1412bcc42)
    #45 0x7ff7f865e28b in `ApplicationMain_obj::create'::`2'::_hx_Closure_1::_hx_run C:\Users\chii\build\stringtest\Export\windows\obj\src\ApplicationMain.cpp:160
    #46 0x7ff7f865e491 in `ApplicationMain_obj::create'::`2'::_hx_Closure_1::__run C:\Users\chii\build\stringtest\Export\windows\obj\src\ApplicationMain.cpp:162
    #47 0x7ff7f81e7c36 in lime::app::_Event_Void_Void_obj::dispatch(void) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140f67c36)
    #48 0x7ff7f7d2e4f6 in lime::utils::Preloader_obj::start(void) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140aae4f6)
    #49 0x7ff7f7d2f214 in lime::utils::Preloader_obj::updateProgress(void) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140aaf214)
    #50 0x7ff7f7d2e113 in lime::utils::Preloader_obj::loadedAssetLibrary(class String) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140aae113)
    #51 0x7ff7f7d2c0ac in lime::utils::Preloader_obj::_hx_isInstanceOf(int) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140aac0ac)
    #52 0x7ff7f7d2ac2d in lime::utils::Preloader_obj::__register(void) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140aaac2d)
    #53 0x7ff7f7345539 in Dynamic::operator()(class Dynamic const &) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1400c5539)
    #54 0x7ff7f85f948b in lime::app::Promise_lime_utils_AssetLibrary_obj::complete(class hx::ObjectPtr<class lime::utils::AssetLibrary_obj>) C:\Users\chii\build\stringtest\Export\windows\obj\src\lime\app\Promise_lime_utils_AssetLibrary.cpp:58
    #55 0x7ff7f85fb26f in lime::app::__Promise_lime_utils_AssetLibrary_objcomplete C:\Users\chii\build\stringtest\Export\windows\obj\src\lime\app\Promise_lime_utils_AssetLibrary.cpp:68
    #56 0x7ff7f87cdc58 in hx::CMemberFunction1::__run(class Dynamic const &) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\DynamicImpl.h:151
    #57 0x7ff7f7345539 in Dynamic::operator()(class Dynamic const &) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1400c5539)
    #58 0x7ff7f7b7bf7c in lime::app::Future_obj::onComplete(class Dynamic) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1408fbf7c)
    #59 0x7ff7f85f9939 in lime::app::Promise_lime_utils_AssetLibrary_obj::completeWith(class hx::ObjectPtr<class lime::app::Future_obj>) C:\Users\chii\build\stringtest\Export\windows\obj\src\lime\app\Promise_lime_utils_AssetLibrary.cpp:72
    #60 0x7ff7f8133e89 in lime::utils::Assets_obj::_hx_isInstanceOf(int) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140eb3e89)
    #61 0x7ff7f81321bd in lime::utils::Assets_obj::__register(void) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140eb21bd)
    #62 0x7ff7f7cadc56 in lime::app::Promise_obj::complete(class Dynamic) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140a2dc56)
    #63 0x7ff7f7cacb3e in lime::app::Promise_obj::__Mark(class hx::MarkContext *) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140a2cb3e)
    #64 0x7ff7f87cdc58 in hx::CMemberFunction1::__run(class Dynamic const &) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\DynamicImpl.h:151
    #65 0x7ff7f7345539 in Dynamic::operator()(class Dynamic const &) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1400c5539)
    #66 0x7ff7f7b7bf7c in lime::app::Future_obj::onComplete(class Dynamic) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1408fbf7c)
    #67 0x7ff7f7b7b50a in lime::app::Future_obj::_hx_isInstanceOf(int) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1408fb50a)
    #68 0x7ff7f7b7afbd in lime::app::Future_obj::__register(void) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1408fafbd)
    #69 0x7ff7f7cadc56 in lime::app::Promise_obj::complete(class Dynamic) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140a2dc56)
    #70 0x7ff7f792f6e1 in lime::net::_HTTPRequest_Bytes_obj::_hx_isInstanceOf(int) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1406af6e1)
    #71 0x7ff7f792f42d in lime::net::_HTTPRequest_Bytes_obj::__register(void) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1406af42d)
    #72 0x7ff7f7345539 in Dynamic::operator()(class Dynamic const &) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1400c5539)
    #73 0x7ff7f857d64b in lime::app::Promise_haxe_io_Bytes_obj::complete(class hx::ObjectPtr<class haxe::io::Bytes_obj>) C:\Users\chii\build\stringtest\Export\windows\obj\src\lime\app\Promise_haxe_io_Bytes.cpp:58
    #74 0x7ff7f7bc5899 in lime::_internal::backend::native::NativeHTTPRequest_obj::localThreadPool_onComplete(class Dynamic) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x140945899)
    #75 0x7ff7f7bbbda3 in lime::_internal::backend::native::NativeHTTPRequest_obj::__Mark(class hx::MarkContext *) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x14093bda3)
    #76 0x7ff7f87ce421 in hx::CStaticFunction1::__run(class Dynamic const &) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\DynamicImpl.h:188
    #77 0x7ff7f7bff9b9 in lime::app::_Event_Dynamic_Void_obj::dispatch(class Dynamic) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x14097f9b9)
    #78 0x7ff7f838ddda in lime::_hx_system::ThreadPool_obj::_hx___update(int) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x14110ddda)
    #79 0x7ff7f838c47d in lime::_hx_system::ThreadPool_obj::__SetField(class String const &, struct cpp::Variant const &, enum hx::PropertyAccessMode) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x14110c47d)
    #80 0x7ff7f87cdc58 in hx::CMemberFunction1::__run(class Dynamic const &) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\DynamicImpl.h:151
    #81 0x7ff7f79fc4d3 in lime::app::_Event_Int_Void_obj::dispatch(int) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x14077c4d3)
    #82 0x7ff7f84b4a7a in lime::_internal::backend::native::NativeApplication_obj::handleApplicationEvent(void) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x141234a7a)
    #83 0x7ff7f84b0b7b in lime::_internal::backend::native::NativeApplication_obj::__Mark(class hx::MarkContext *) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x141230b7b)
    #84 0x7ff7f87cdb1b in hx::CMemberFunction0::__run(void) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\DynamicImpl.h:54
    #85 0x7ff7f877e54f in val_call0 C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\CFFI.cpp:685
    #86 0x7ffeebf27dd7 in lime_curl_version_info__prime (C:\Users\chii\build\stringtest\Export\windows\bin\lime.ndll+0x180047dd7)
    #87 0x7ffeebf285d9 in lime_curl_version_info__prime (C:\Users\chii\build\stringtest\Export\windows\bin\lime.ndll+0x1800485d9)
    #88 0x7ffeebf2767d in lime_curl_version_info__prime (C:\Users\chii\build\stringtest\Export\windows\bin\lime.ndll+0x18004767d)
    #89 0x7ff7f84b46ed in lime::_internal::backend::native::NativeApplication_obj::exec(void) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1412346ed)
    #90 0x7ff7f7a133f3 in lime::app::Application_obj::exec(void) (C:\Users\chii\build\stringtest\Export\windows\bin\AddingAnimation.exe+0x1407933f3)
    #91 0x7ff7f865befd in ApplicationMain_obj::create(class Dynamic) C:\Users\chii\build\stringtest\Export\windows\obj\src\ApplicationMain.cpp:252
    #92 0x7ff7f8656dd0 in ApplicationMain_obj::main(void) C:\Users\chii\build\stringtest\Export\windows\obj\src\ApplicationMain.cpp:143
    #93 0x7ff7f8720420 in __hxcpp_main C:\Users\chii\build\stringtest\Export\windows\obj\src\__main__.cpp:24
    #94 0x7ff7f8720732 in WinMain C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\HxcppMain.h:93
    #95 0x7ff7f8addac1 in invoke_main d:\a01\_work\20\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:102
    #96 0x7ff7f8addac1 in __scrt_common_main_seh d:\a01\_work\20\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #97 0x7fff44f34ecf  (C:\WINDOWS\System32\KERNEL32.DLL+0x180014ecf)
    #98 0x7fff45bae39a  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18007e39a)

Address 0x00795d8f4ba0 is located in stack of thread T0 at offset 0 in frame
    #0 0x7ff7f8897aef in GlobalAllocator::GetFreeBlock(int, class hx::ImmixAllocator *) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:3490

  This frame has 1 object(s):
    [32, 33) 'forceCompact'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp, SEH and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-underflow C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:5554 in hx::MarkConservative(int *, int *, class hx::MarkContext *)
Shadow bytes around the buggy address:
  0x02407e69e920: f3 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02407e69e930: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02407e69e940: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02407e69e950: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02407e69e960: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x02407e69e970: 00 00 00 00[f1]f1 f1 f1 01 f3 f3 f3 f3 00 00 00
  0x02407e69e980: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02407e69e990: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02407e69e9a0: f1 f1 f1 f1 f8 f3 f3 f3 f3 00 00 00 00 00 00 00
  0x02407e69e9b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02407e69e9c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==88280==ABORTING
</pre>
</details>

**Comment by space-nuko** [comment]
Actually I think this is an hxcpp issue, closing
